### ISSUE TITLE
Package 1.6.9 missing directory old/bin/

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/pkg-ledgersmb#4]

**Comment by Diabolistic** [comment]
After having a chat with ehuelsmann yesterday on riot we came to the conclusion that i was having a bug caused by this exact issue.
The package installed fine and seemed to be working until i had several menu options giving me a generic "An error has occured!" popup without any further explanation or hints as to what might have been the issue.

After examining the "`journalctl -xu ledgersmb`" is also notices several lines with:
`Apr 07 12:52:51 wh004 starman[10289]: Failed to execute old/bin/old-handler.pl (No such file or directory):`
after copying the old/bin/ from github to the local installation all menu options (so far) seem to be working correctly.

**Comment by ehuelsmann** [comment]
@Diabolistic thanks ! Did you report to Debian too?
